import type { Jogo } from "@/types";

export const MOCK_JOGOS: Jogo[] = [
  {
    id: "1",
    user_id: "demo",
    nome: "The Witcher 3: Wild Hunt",
    plataforma: "PC",
    genero: "RPG",
    nota: 9.8,
    status: "Concluído",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "demo",
    nome: "Elden Ring",
    plataforma: "PS5",
    genero: "RPG",
    nota: 9.5,
    status: "Jogando",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "demo",
    nome: "Hades",
    plataforma: "Nintendo Switch",
    genero: "Ação",
    nota: 9.2,
    status: "Concluído",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co27vp.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    user_id: "demo",
    nome: "Cyberpunk 2077",
    plataforma: "PC",
    genero: "RPG",
    nota: 8.5,
    status: "Concluído",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4hp9.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    user_id: "demo",
    nome: "Hollow Knight",
    plataforma: "PC",
    genero: "Indie",
    nota: 9.0,
    status: "Jogando",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rgi.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    user_id: "demo",
    nome: "God of War: Ragnarök",
    plataforma: "PS5",
    genero: "Ação",
    nota: 9.7,
    status: "Concluído",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5s5v.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    user_id: "demo",
    nome: "Forza Horizon 5",
    plataforma: "Xbox",
    genero: "Corrida",
    nota: 8.8,
    status: "Jogando",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3ofx.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    user_id: "demo",
    nome: "Resident Evil Village",
    plataforma: "PC",
    genero: "Terror",
    nota: 8.2,
    status: "Abandonado",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2uo0.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    user_id: "demo",
    nome: "Zelda: Tears of the Kingdom",
    plataforma: "Nintendo Switch",
    genero: "Aventura",
    nota: 9.6,
    status: "Quero Jogar",
    capa_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6cl1.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    user_id: "demo",
    nome: "FIFA 24",
    plataforma: "PS5",
    genero: "Esporte",
    nota: 6.5,
    status: "Abandonado",
    capa_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "11",
    user_id: "demo",
    nome: "Starfield",
    plataforma: "Xbox",
    genero: "RPG",
    nota: 7.0,
    status: "Abandonado",
    capa_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "12",
    user_id: "demo",
    nome: "Dead Cells",
    plataforma: "Mobile",
    genero: "Indie",
    nota: 8.8,
    status: "Concluído",
    capa_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
